version: 0.2

env:
  secrets-manager:
    dockerUser: "dockerSecret:dockerUser"
    dockerEmail: "dockerSecret:dockerEmail"
    dockerPass: "dockerSecret:password"

phases:
  install:
    runtime-versions:
      python: 3.8
    
  pre_build:
    commands: 
      - echo in pre_build phase
      - aws --version
      - BASE=489724165018.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo $BASE
      - docker login --username $dockerUser --password $dockerPass
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $BASE
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo 
      
  build:
    commands:
      - echo Build started
      - docker build -t mynginx:latest ./nginx
      - docker build -t mypyweb:latest ./flaskcode
      - docker build -t mymysql:latest ./mysql
      - docker tag mynginx:latest $BASE/nginx:latest
      - docker tag mypyweb:latest $BASE/pyweb:latest
      - docker tag mymysql:latest $BASE/mysql:latest     
      
  post_build:
    commands:
    - echo pushing docker images to ECR
    - docker push $BASE/nginx:latest
    - docker push $BASE/pyweb:latest
    - docker push $BASE/mysql:latest
  