
version: '3.3'
networks:
  webapp:

services:
  nginx:
    
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: mynginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - pyweb
    #network_mode: host
    networks:
      - webapp

  pyweb:
    build:
      context: ./flaskcode
      dockerfile: Dockerfile
    container_name: mypyweb
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: webhook.py
    
    networks:
      - webapp
        
    

  mysql:
    image: mysql:latest
    build:
      context: ./mysql
    container_name: mymysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql:/usr/share/nginx/html
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/:ro
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: mypass
      TZ: Asia/Tokyo
    networks:
      - webapp
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

#  adminer:
#    image: adminer:latest
#    container_name: myadminer
#    restart: always
#    ports:
#      - "8000:8000"
#    networks:
#      - webapp
      
      